name: tooka
base: core24
version: git
summary: A fast, rule-based CLI tool for organizing your files.
description: Tooka is a powerful file automation tool that helps you organize, rename, move, copy, compress, or delete files using rules written in simple YAML format.
icon: tooka.svg
grade: stable
confinement: strict
platforms:
  amd64:
  arm64:
  armhf:
  riscv64:
  

parts:
  tooka:
    plugin: rust
    source: .
    rust-channel: "stable"

  desktop-files:
    plugin: dump
    source: data
    organize:
      tooka.desktop: usr/share/applications/tooka.desktop
      tooka.svg: usr/share/applications/tooka.svg

apps:
  tooka:
    command: bin/tooka
    plugs:
      - home
      - removable-media
      - optical-drive
